#DJ, 1st, Turtle Race
import turtle
import random
import time
screen = turtle.Screen()
screen.setup(600,400)
screen.title("Turtle Race")
screen.bgcolor("gray")
t1 = turtle.Turtle()
t2 = turtle.Turtle()
t3 = turtle.Turtle()
t4 = turtle.Turtle()
t5 = turtle.Turtle()
t1.color("RoyalBlue4")
t1.shape("turtle")
t1.teleport(-250,150)
t2.color("orchid")
t2.shape("turtle")
t2.teleport(-250,75)
t3.color("PaleTurquoise1")
t3.shape("turtle")
t3.teleport(-250,0)
t4.color("PaleGreen")
t4.shape("turtle")
t4.teleport(-250,-75)
t5.color("purple")
t5.shape("turtle")
t5.teleport(-250,-150)
turtle.exitonclick()